on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - services/client/**
  pull_request:
    branches:
      - main
    paths:
      - services/client/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn run export
